version: '3.8'

services:
  frontend-link:
    image: robertmuldoon/frontend-link:latest
    ports:
      - "8080:8080"
    networks:
      - my_network

  db-link:
    image: robertmuldoon/backend-link:latest
    ports:
      - "8081:8081"
    networks:
      - my_network

  map-frontend:
    image: robertmuldoon/map_frontend:latest
    ports:
      - "3000:3000"
    networks:
      - my_network



networks:
  my_network:
    driver: bridge
